### ISSUE TITLE
load chat faster

### ISSUE THREAD

**Issue by tinnus-napbus** [uqbar-dao/pongo-app#7]
it takes a 2 or 3 seconds on my phone to open a chat after clicking on it. Ideally it would open instantly, displaying old cached messages immediately and then if it needs to retrieve newer ones it should load them async

**Comment by willbach** [comment]
1) what phone OS do you have?
2) Is this after going to the chat in current session? Or after opening app from a closed state?

**Comment by tinnus-napbus** [comment]
1. android
2. after opening app from a closed state it seems

**Comment by willbach** [comment]
The app has been updated to persist chat data. Have you seen any improvement?

**Comment by tinnus-napbus** [comment]
yes it seems much faster

I also got a new phone though so that might have helped

**Comment by willbach** [comment]
Cool. I'll advise anyone who has this issue in the future to get a new phone.
