### ISSUE TITLE
member mention selector list overflows/ past chat input on desktop ui

### ISSUE THREAD

**Issue by tinnus-napbus** [uqbar-dao/pongo-app#8]
also looks slightly too low on mobile, but desktop in particular is messed up

**Comment by willbach** [comment]
That's because you're supposed to swipe up on it to see more suggestions :). I'll add an indicator

**Comment by tinnus-napbus** [comment]
this is what it does on desktop to be clear:

![2023-03-29_09h45m00s](https://user-images.githubusercontent.com/77721746/228362573-92f8924c-f1ea-42e5-aa5d-7d68112f1b47.png)

**Comment by willbach** [comment]
Fixed in v1.0.3
